name: Cloudland
favicon: null
layout_spectrum: 0.3572774308267981
typography_spectrum: 0.5956591623835266
title: We run together. // Cloudland Caps and hats
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: "<script>   (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){   (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),   m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)   })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');    ga('create', 'UA-76609748-1', 'auto');   ga('send', 'pageview');  </script>"
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8002877349499613
  lightness: 0.17098410497419536
  saturation: 0.894585571018979
  rhythmicContrast: 0.2708180567715317
purpose: []
